table EfficiencyTarget
	lineageTag: 8606310b-4742-4637-b17b-b7ac752667e0

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5df39f51-4f87-4b89-80d2-67ba1129e36b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column EfficiencyTarget
		dataType: double
		lineageTag: 2702ac4a-d3cd-42db-b7b5-7ac79540909e
		summarizeBy: sum
		sourceColumn: EfficiencyTarget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition EfficiencyTarget = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjIwMlHSUTLQMTBXitUB800hfFMY3wzOjwUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Year = _t, EfficiencyTarget = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Year", Int64.Type}, {"EfficiencyTarget", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

